# Generated by Django 5.2 on 2025-09-10 17:55

import django.db.models.deletion
import django_jalali.db.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomMtoMLike',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time_create', django_jalali.db.models.jDateTimeField(auto_now_add=True)),
                ('to_like', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='to_like', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Posts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=300, null=True)),
                ('slug', models.SlugField()),
                ('bad_admin', models.BooleanField(default=True)),
                ('time_create', django_jalali.db.models.jDateTimeField(auto_now_add=True)),
                ('time_update', django_jalali.db.models.jDateTimeField(auto_now=True)),
                ('like', models.ManyToManyField(related_name='like_post_user', through='posts.CustomMtoMLike', to=settings.AUTH_USER_MODEL)),
                ('marke', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='marke_post', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Images',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='images_post')),
                ('time_create', django_jalali.db.models.jDateTimeField(auto_now_add=True)),
                ('time_update', django_jalali.db.models.jDateTimeField(auto_now=True)),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='image_post', to='posts.posts')),
            ],
        ),
        migrations.AddField(
            model_name='custommtomlike',
            name='like_to',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='like_to', to='posts.posts'),
        ),
        migrations.CreateModel(
            name='Comments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.TextField(max_length=2000)),
                ('time_create', django_jalali.db.models.jDateTimeField(auto_now_add=True)),
                ('time_update', django_jalali.db.models.jDateTimeField(auto_now=True)),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comment_post', to='posts.posts')),
            ],
        ),
    ]
