# Generated by Django 5.2 on 2025-09-14 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('acconts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userx',
            name='is_verified',
            field=models.BooleanField(default=False),
        ),
    ]
